### ISSUE TITLE
DateTime.now not passing wont allow other values test for #Types::Fixnum and Types::Float

### ISSUE THREAD

**Issue by sbaha88** [jodigiordano/parameters_schema#1]
Hi there,
Thanks for developing this gem. I find it more useful than strong_params.
I originally wanted to create a pull but decided not to because of one line of code. I am not sure about proper etiquette here on github.
So, the issue is that test_schema_types.rb failed on "wont allow other values" test for Fixnum and Float.  It was because of DateTime.now in the array. To fix this I added:
`return false if self.kind_of?(Date)`
in the `numeric?` method of core_ext.rb
Cheers

**Comment by jodigiordano** [comment]
Hi @sbaha88, thanks for you report.
An issue or a pull request is fine.
In either cases, I'll validate it, update the gem and release a new version.

I looked at the code of `numeric?` and it may return `true` for a `Date` or `DateTime` if the `.to_s` of those objects return a value with only `[0-9]` in it. It can happen if the default output for `to_s` of those objects is altered.

Instead of `return false if self.kind_of?(Date)`, I will drop the line `return true if self.to_s =~ /^\d+$/` as the next line `Float(self)` does the same thing and won't allow a `Date` or `DateTime` object.

I think it is OK to do this because normally, if you request a field to be numeric, you don't want to accept an object which `to_s` looks like numeric.

**Comment by jodigiordano** [comment]
Fixed in `1.0.2` :)

**Comment by sbaha88** [comment]
Nice, great job with the gem)
